-- Run this once in the Supabase SQL Editor for the project used by the app.
create table if not exists public.analyses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  filename text not null,
  ats_score numeric not null default 0,
  keyword_match numeric not null default 0,
  missing_keywords jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  analysis_result jsonb not null default '{}'::jsonb
);

create index if not exists analyses_user_id_created_at_idx
on public.analyses(user_id, created_at desc);

alter table public.analyses enable row level security;

-- The backend uses the Supabase service-role key for these REST operations,
-- so no client-side INSERT/SELECT policies are required for the current architecture.
